### PR TITLE
fix: "git+ssh" in package.json breaks npm install for folks w/o ssh keys

### PR DESCRIPTION
**Pull request by lostfictions**

### CODE REVIEW

**Comment by lostfictions** [comment]
oops, ok

**Comment by lostfictions** [comment]
yeah, any repo-ish convention is fine, it's not platform-specific. if Samvel was using a different git client that defaulted to https instead of ssh he'd have had the same problem i think

**Comment by lostfictions** [comment]
you can even use just `RepoOwner/repo-name#branch`, no need for `github:` afaik

**Comment by anri-asaturov** [comment]
ok, i'll try it

**Pull request closed without merging**
