### PR TITLE
fix: Medcryptor UI bugs

### PR DESCRIPTION
**Pull request by suprko**
#### Relevant info and issue/PR links
https://app.clubhouse.io/peerio/story/16861/mc-desktop-whitelabel-issues
also the last 3 commits to `medcryptor-desktop` (already merged) https://github.com/PeerioTechnologies/medcryptor-desktop/commits/master

#### Testing instructions
fixed:
1. Medcryptor logo on welcome page (fixed on `medcryptor-desktop` repo)
1. added spacing around logo on Login
1. "Where to find Account Key" link removed on whitelabels (it's a Peerio-specific link)
1. fixed text colour for unread ChatList items in Medcryptor
1. remove "Create Account" button from Medcryptor

----
### Repository owner

- [ ] Was tested and can be merged.
- [ ] PR name follows conventional changelog format.

[PR guideline](https://github.com/PeerioTechnologies/peerio-icebear/blob/dev/docs/CONTRIBUTING.md)

### CODE REVIEW

**Comment by anri-asaturov** [comment]
How dare you not to please eslint!

**Comment by ebilg** [comment]
one last change needed, see comment on CH

**Comment by suprko** [comment]
^ just pushed the fix

**Comment by ebilg** [comment]
can be merged

**Comment by anri-asaturov** [comment]
] src/ui/login/NewAccountButton.tsx
[test:obs-dec  ] Found components without @observer decorator

**Pull request merged**
