### PR TITLE
feat: new avatar colors

### PR DESCRIPTION
**Pull request by suprko**
#### Relevant info and issue/PR links 
CH https://app.clubhouse.io/peerio/story/9949/desktop-update-avatar-colors
 icebear https://github.com/PeerioTechnologies/peerio-icebear/pull/236
PeerUI https://github.com/PeerioTechnologies/ui-library/pull/4

#### Testing instructions  
note: after merging icebear, wait for new PeerUI release, then I'll version bump PeerUI here and then it will be ready for merge

----
### Repository owner

- [ ] Was tested and can be merged.
- [ ] PR name follows conventional changelog format.

[PR guideline](https://github.com/PeerioTechnologies/peerio-icebear/blob/dev/docs/CONTRIBUTING.md)

### CODE REVIEW

**Comment by ebilg** [comment]
waiting on icebear/mobile

**Comment by seavan** [comment]
@Karim94 ^

**Comment by suprko** [comment]
not urgent actually. apparently we are going to wait until we have the release notes dialog, so that users aren't confused that their contacts are all changing colours.

**Comment by Karim94** [comment]
PR is made anyways, we can merge whenever we are ready.

**Comment by ebilg** [comment]
can be merged

**Comment by anri-asaturov** [comment]
@suprko this branch refers to peer-ui branch,  sdk already merged, fix this so i can merge

**Pull request merged**
