### PR TITLE
style(UserPicker): 'exact match' search result header

### PR DESCRIPTION
**Pull request by suprko**
#### Relevant info and issue/PR links 
https://app.clubhouse.io/peerio/story/3187/desktop-add-a-header-for-contact-exact-match
 copy: https://github.com/PeerioTechnologies/peerio-icebear/pull/151

#### Testing instructions  
This PR adds the "Exact match" header to the user search result when you get an exact username/email match. Also, filtered Favourites and All Contacts now remain visible when an Exact Match is found, and Exact Match appears below them.

This addition makes it slightly strange to search for a user outside of your contacts when creating a new Room. @mmfoscarpeerio is creating a separate story to redesign the room user search flow to bring it more in line with this one.

----
### Repository owner

- [ ] Was tested and can be merged.
- [ ] PR name follows conventional changelog format.

[PR guideline](https://github.com/PeerioTechnologies/peerio-icebear/blob/dev/docs/CONTRIBUTING.md)

### CODE REVIEW

**Comment by suprko** [comment]
A couple of questions for design, 1 moment...

**Comment by suprko** [comment]
@anri-asaturov reopened, ready for review

**Comment by ebilg** [comment]
acceptance criteria not met, I've commented in CH

**Comment by anri-asaturov** [comment]
Something goes on with this, or..?

**Comment by suprko** [comment]
Blocked, waiting for design to tell us how to fix the New Room user search and then we can add this to both New Room and New DM

**Pull request closed without merging**
