### PR TITLE
fix: allow creating folders in folder selection dialog

### PR DESCRIPTION
**Pull request by dchest**
#### Testing instructions  

----
### Repository owner

- [ ] Was tested and can be merged.
- [ ] PR name follows conventional changelog format.

[PR guideline](https://github.com/PeerioTechnologies/peerio-icebear/blob/dev/docs/CONTRIBUTING.md)

### CODE REVIEW

**Comment by anri-asaturov** [comment]
Why would you create folder when picking files to upload?

**Comment by dchest** [comment]
This is one is used in `downloadFolder`, not for uploading (that one is called `pickLocalFiles`).

**Comment by dchest** [comment]
Also, the button label is `Open`, should we set it to `Save` or `Download`? In which case it's probably better to rename `selectFolder` to `selectFolderToDownloadInto` or something.

**Comment by dchest** [comment]
^ made the changes, pls re-review

**Pull request merged**
