### PR TITLE
feat: refactor patient spaces

### PR DESCRIPTION
**Pull request by alexandra-marin**
#### Relevant info and issue/PR links 
 https://app.clubhouse.io/peerio/story/9214/sdk-refactor-patient-space-to-support-mobile
#### Testing instructions  
Have moved to icebear: common parts used for desktop + mobile: active space props, room type helpers, contact filtering
Have not moved: creating spaces logic (not needed for mobile)

----
### Repository owner

- [ ] Was tested and can be merged.
- [ ] PR name follows conventional changelog format.

[PR guideline](https://github.com/PeerioTechnologies/peerio-icebear/blob/dev/docs/CONTRIBUTING.md)

### CODE REVIEW

**Comment by ebilg** [comment]
will test when icebear PR is approved

**Comment by anri-asaturov** [comment]
Resolve conflicts plz

**Comment by ebilg** [comment]
get an error when backing out from a patient space

**Comment by ebilg** [comment]
signing in to existing doc account gives blue screen logs attached to CH task

**Comment by ebilg** [comment]
can be merged

**Pull request merged**
