### PR TITLE
chore: more TypeScript conversion

### PR DESCRIPTION
**Pull request by suprko**
#### Relevant info and issue/PR links
https://github.com/PeerioTechnologies/peerio-icebear/pull/377

#### Testing instructions
Behind-the-scenes update, shouldn't have changed anything, ideally hasn't broken anything :crossed_fingers: 

Affected views/components:

Regular app
* New Room
* New DM
* Pending DM (when invited via email)
  * Pending DM dismissed
*  Share-to-chat in progress (progress bar thing at bottom of chat)
* UrlPreview first consent
* Contacts view
  * Contact list
  * Invited contacts list
  * New contact view

Medcryptor
* Chat
  * Patient List sidebar
* New Room
* Login view

----
### Repository owner

- [ ] Was tested and can be merged.
- [ ] PR name follows conventional changelog format.

[PR guideline](https://github.com/PeerioTechnologies/peerio-icebear/blob/dev/docs/CONTRIBUTING.md)

### CODE REVIEW

**Comment by suprko** [comment]
arg. test failed because I didn't push my icebear changes first :weary:

**Comment by suprko** [comment]
Oh yeah, a quick note on the things I didn't convert. There are a few components that rely on ValidatedInput and BetterInput. BetterInput has some weird type conflicts with the Input component itself (e.g. the `onChange` prop) though I think it could be massaged into the right shape. ValidatedInput, though, does this weird thing where it programmatically adds properties to its parent class (e.g. it adds `emailValid` and `emailDirty` to `ProfileStore`), which obviously does not cooperate with TS... So I'm not sure we can convert that without a total rewrite.

**Comment by anri-asaturov** [comment]
still failing ci @suprko

**Comment by suprko** [comment]
@anri-asaturov "Socket timeout", not sure if this is actually our tests? Can you try a rebuild?

**Comment by anri-asaturov** [comment]
@lostfictions merging this for logistics reasons, i guess we'll be overhauling are reviewing everything in the next months anyway

**Pull request merged**
