### PR TITLE
style: misc small CSS fixes

### PR DESCRIPTION
**Pull request by suprko**
#### Relevant info and issue/PR links 
 https://app.clubhouse.io/peerio/story/1902/desktop-upload-dialog-has-inconsistent-username
https://app.clubhouse.io/peerio/story/2149/desktop-alignment-of-file-name

#### Testing instructions  
IMO none needed if code is good (e.g. `targetTitle` function in UploadDialog). Most significant fixes are to UploadDialog to match new mockups. Other very minor changes to spacing, font-weight, etc.

----
### Repository owner

- [ ] Was tested and can be merged.
- [ ] PR name follows conventional changelog format.

[PR guideline](https://github.com/PeerioTechnologies/peerio-icebear/blob/dev/docs/CONTRIBUTING.md)

### CODE REVIEW

**Comment by suprko** [comment]
didn't notice there were many more small CSS fixes in the backlog. will group them all together and reopen PR when they're done

**Comment by suprko** [comment]
@anri-asaturov reopened, ready for review

**Comment by anri-asaturov** [comment]
fix the conflict plz

**Comment by suprko** [comment]
@anri-asaturov done

**Pull request merged**
