### PR TITLE
fix: do not allow doctor to be room admin in patient spaces

### PR DESCRIPTION
**Pull request by suprko**
#### Relevant info and issue/PR links 
 https://app.clubhouse.io/peerio/story/7834/desktop-remove-clerk-s-ability-to-promote-doctor-to-admin
https://github.com/PeerioTechnologies/peerio-icebear/pull/224

#### Testing instructions  
In Patient Room or Internal Room, invite a doctor to join the room and have the doctor join. In the room sidebar, check the menu next to the doctor's name; the option to promote to admin should not be there.

----
### Repository owner

- [ ] Was tested and can be merged.
- [ ] PR name follows conventional changelog format.

[PR guideline](https://github.com/PeerioTechnologies/peerio-icebear/blob/dev/docs/CONTRIBUTING.md)

### CODE REVIEW

**Comment by suprko** [comment]
@flohdot this currently works: doctors cannot be promoted to room admin inside patient spaces. Just wondering if you wanted this to be true for all non-clerks, or just doctors? For example, can patients be room admins?

**Comment by ebilg** [comment]
no reviewers listed

**Comment by ebilg** [comment]
did not work

**Comment by ebilg** [comment]
can be merged AFTER TODAYS RELEASE

**Comment by anri-asaturov** [comment]
Release branch is frozen (master)

**Pull request merged**
