### PR TITLE
feat: new PeerUI SearchInput component

### PR DESCRIPTION
**Pull request by suprko**
#### Relevant info and issue/PR links
https://app.clubhouse.io/peerio/story/17070/desktop-use-new-searchinput-component

#### Testing instructions
PeerUI has a new SearchInput component to replace the kinda hacky ways we were faking a search input in the app and copy-pasting tons of code. I also took this opportunity to do a bit of cleanup of some of the search JSX and CSS, e.g. removing the weird `chip-wrapper.scss` standalone file, un-nesting user search in a few places, and consolidating or removing old search input styles.

Functionality it should be the same as before, but there is a minor styling update to the input -- the corners are less rounded. They have a 4px border-radius, matching the previous Input update, instead of the fully semi-circle 24px border-radius.

Here's where SearchInput has been used:
* Contacts list
* NewContact search/invite
* Emoji search
* File picker (share-to-chat from Peerio files)
* Files view search bar
* Move file dialog
* Share dialog: in Files, click three-dots menu next to any file, click Share
* Share dialog: drag-and-drop multiple files into a chat, then click the "edit share" icon)
* User search in both new DM and new channel

----
### Repository owner

- [ ] Was tested and can be merged.
- [ ] PR name follows conventional changelog format.

[PR guideline](https://github.com/PeerioTechnologies/peerio-icebear/blob/dev/docs/CONTRIBUTING.md)

### CODE REVIEW

**Comment by ebilg** [comment]
two things look a little off
1. emoji search
old
screen shot 2018-11-20 at 3 21 30 pm
new
screen shot 2018-11-20 at 3 21 36 pm

2. move dialog in files tab
old
screen shot 2018-11-20 at 3 25 46 pm
new
screen shot 2018-11-20 at 3 25 31 pm
it's also super jarringly blocky
😿

**Comment by suprko** [comment]
@ebilg emoji search has been fixed. move dialog doesn't repro for me, I think it's because i pushed a styling fix to PeerUI a little bit after releasing v4.1.0 so you may need to `npm update peer-ui` to see it?

**Comment by ebilg** [comment]
commented on CH

**Comment by suprko** [comment]
@ebilg fixed. also adjusted the spacing between the dialog title and the search input, it's not meant to be as tall as it is on prod.

**Comment by ebilg** [comment]
can be merged

**Comment by anri-asaturov** [comment]
prettier error

**Pull request merged**
