### PR TITLE
feat: clicking notification opens the correct DM/room

### PR DESCRIPTION
**Pull request by dchest**
These three lines to activate the chat I copied from ChatList 😢  Since I don't know what's going on there, suggestions on how to refactor this into one place are welcome.

[PR guideline](https://github.com/PeerioTechnologies/peerio-icebear/blob/dev/docs/CONTRIBUTING.md)

#### Relevant issue tracker links  

https://peerio.tpondemand.com/entity/7595

#### Manual testing instructions  

0. Put Peerio into background.
1. Wait for notification.
2. Click on it.

What it did before: Peerio activates, but shows in the same place where you left it.

What it should do now: Peerio activates and navigates to the DM or room this notification is coming from.

----
### Reviewer

* Localisation.
* Architectural decisions.
* Performance.
* Comments.
* Big feature tech design documentation.
* Readability.
* DRY.
* Can we extract something to SDK?
* Are there any bicycles invented that should be replaced with existing SDK
* Are there unit and e2e tests added?

----
### Repository owner

- [ ] At least one approved code review exists.
- [ ] Approved tester review exists and was done after last code changes.
- [ ] CI build and tests passed.
- [ ] This feature/bugfix is considered fully done and can get merged.
- [ ] PR name follows conventional changelog format.
- [ ] I'll remember to squash commits.

### CODE REVIEW

**Comment by dchest** [comment]
Wait, there's something else to add.

**Comment by anri-asaturov** [comment]
And i'll refactor isInChatsView setting in this branch. Have an idea

**Comment by anri-asaturov** [comment]
I think it got better with clientApp.isInChatsView, @dchest  ;)

**Comment by anri-asaturov** [comment]
@ebilg this is ready to test, multiplatform test is needed

**Comment by dchest** [comment]
@anri-asaturov yes, looks nicer. Thanks :)

**Comment by dchest** [comment]
Thanks @ebilg. I'm gonna test it today, but it looks like it's an Electron issue: https://github.com/electron/electron/issues/2867

I'll try switching to another notification API (this uses HTML5 Notification, but we can also use Electron's own Notification) to see if it fixes it (we'll need it anyway if we want to implement replies from notification on macOS).

**Comment by anri-asaturov** [comment]
@dchest just focus window in the notification 'onclick' handler?

**Comment by dchest** [comment]
@anri-asaturov it's what it does right now. But `focus()` is broken in Windows 10 — see link.

**Comment by dchest** [comment]
ah, it calls `app.focus()`, not `window.focus()`. Will try various permutations :)

**Comment by dchest** [comment]
Yay, made them work on Windows. @ebilg please test again.

**Pull request merged**
