### PR TITLE
fix: MigrationDialog text

### PR DESCRIPTION
**Pull request by suprko**
#### Relevant info and issue/PR links 
https://app.clubhouse.io/peerio/story/8402/deskto-change-file-migration-description-to-a-single-string-instead-of-separating-the-download-link
https://app.clubhouse.io/peerio/story/8575/desktop-migration-dialog-update-2

#### Testing instructions  
Migration dialog: 
1. In main description text, the third paragraph should be fixed now
2. New "Did you know?" line and updated copy during migration-in-progress

----
### Repository owner

- [ ] Was tested and can be merged.
- [ ] PR name follows conventional changelog format.

[PR guideline](https://github.com/PeerioTechnologies/peerio-icebear/blob/dev/docs/CONTRIBUTING.md)

### CODE REVIEW

**Comment by flohdot** [comment]
took care of the sdk side of this with https://github.com/PeerioTechnologies/peerio-icebear/commit/e72b59b7cede21ede51b218c1ca31809966ac512

**Comment by ebilg** [comment]
not working

**Comment by seavan** [comment]
@ebilg it uses an SDK branch, probabky that's the reason it wasn't working for you:

image

**Comment by suprko** [comment]
Updated to include the entire MigrationDialog text update, please re-review real quick

**Comment by ebilg** [comment]
can be merged

**Pull request merged**
