### PR TITLE
feat: closure notices

### PR DESCRIPTION
**Pull request by suprko**
#### Relevant info and issue/PR links
https://app.clubhouse.io/peerio/story/18485/desktop-app-load-notice-of-closure
https://app.clubhouse.io/peerio/story/18521/desktop-service-outage-forever-banner
https://app.clubhouse.io/peerio/story/18524/desktop-account-settings-upgrade-changes
https://app.clubhouse.io/peerio/story/18475/desktop-profile-settings-upgrade-changes
https://app.clubhouse.io/peerio/story/18519/desktop-top-drawer-notice-in-files-tab
https://app.clubhouse.io/peerio/story/18517/desktop-sign-up-notice-of-closure
https://github.com/PeerioTechnologies/peerio-icebear/pull/378

Figma https://www.figma.com/file/f8wf0Mm4m91o6hpN6Joaurjl/18363%3A-In-app-banner-announcing-closure-of-service?node-id=13%3A1

#### Testing instructions
Closure notices *everywhere*

* redesign of NewUser screen (open app with no saved user)
* banner on Login screen
* banner on first step of CreateAccount
* full-page overlay every time you log in (including account creation)
* banner on Chats view
* banner in Settings view, which cannot be dismissed
  * note: on Figma it still shows the "Dismiss" button but there's a conversation between me and Kristina where she said dismiss should not be allowed in the Settings banner 
* "Upgrade" in main menu changed to "Peerio Closure"

NOTE: since we made this so quickly there are some inconsistencies in the documentation/feature requests... I erred on the side of Clubhouse being correct, followed by Figma.

----
### Repository owner

- [ ] Was tested and can be merged.
- [ ] PR name follows conventional changelog format.

[PR guideline](https://github.com/PeerioTechnologies/peerio-icebear/blob/dev/docs/CONTRIBUTING.md)

### CODE REVIEW

**Comment by suprko** [comment]
Test is failing because it needs a copy update from https://github.com/PeerioTechnologies/peerio-icebear/pull/378

Couldn't easily force a string without breaking types in a few places in this component

**Comment by suprko** [comment]
Aha. Tests are failing because of the new overlay on the Chat window, which is indeed supposed to show up on every single login. Is there a way to hide this only during testing? (is there a `testing` flag in `config`?) If not, I can add a click on the overlay to our tests.

**Comment by ebilg** [comment]
just one issue - missing link to account creation from here
Mock:
sign in
Implementation:
screen shot 2019-01-21 at 11 55 12 am

**Comment by ebilg** [comment]
can be merged

**Pull request merged**
