### PR TITLE
fix: make sure NewContact UI draws over illustration

### PR DESCRIPTION
**Pull request by suprko**
#### Relevant info and issue/PR links
https://app.clubhouse.io/peerio/story/16865/desktop-email-invite-button-broken-on-contact-page

#### Testing instructions
NewContact illustration should be in the background now, should not interfere with "invite elsewhere" or "email invite" buttons

----
### Repository owner

- [ ] Was tested and can be merged.
- [ ] PR name follows conventional changelog format.

[PR guideline](https://github.com/PeerioTechnologies/peerio-icebear/blob/dev/docs/CONTRIBUTING.md)

### CODE REVIEW

**Comment by ebilg** [comment]
can be merged

**Comment by suprko** [comment]
there may be a text edit to this. 1 sec

**Comment by anri-asaturov** [comment]
If it's a patch to RC this should be a PR to master branch

**Comment by suprko** [comment]
Drive by text edit :D The old "You have no pending invites..." text wasn't actually removed before, it is now.

Changed base to `master`

**Pull request merged**
