### PR TITLE
chore(deps): update deps

### PR DESCRIPTION
**Pull request by dchest**
Remove electron-rebuild
Update electron-builder to 19.19.1
Update @peerio/updater to 0.2.0

### CODE REVIEW

**Comment by dchest** [comment]
Github hides any word starting with @ maybe thinking it's username. Can't write -AT-peerio/updater🙈

**Comment by anri-asaturov** [comment]
`@peerio/peerio-updater`

**Comment by anri-asaturov** [comment]
success! )

**Comment by dchest** [comment]
Yeah, but the PR message, comes directly from commit messages and is not `code`, so unless you manually edit it, it will hide `@blabla` :/

**Pull request merged**
